version: '2'
services: 
  master:
    image: sequenceiq/spark
    hostname: master
    ports:
    - "4040:4040"
    - "8042:8042"
    - "8080:8080"
    - "8088:8088"
    restart: always
    command: bash /usr/local/spark/sbin/start-master.sh && ping localhost > /dev/null
  worker:
    image: sequenceiq/spark
    links:
    - master:master
    expose: 
    - "8081"
    restart: always
    command: bash /usr/local/spark/sbin/start-slave.sh spark:..master:7077 && ping localhost > /dev/null
